const data = [
    {
        id: 1,
        "for": "мужу",
        "developments": "свадьба",
        "collection": "коллекции",
        "season": "летом",
        "brand": "Zoodamall",
        "price": "10",
        "rarity": "5",
        "img": "https://zoodmall.com/cdn-cgi/image/w=600,fit=contain,f=auto/https://ae01.alicdn.com/kf/He102dd361df24bc1854fe39c219fde172/Luxury-Brand-Big-Golden-Finger-Rings-for-Men-Women-Fine-Jewelry-Cubic-Zircon-Micro-Paved-Rhinestone.jpg",
    },
    {
        id: 2,
        "for": "жене",
        "developments": "для себя",
        "collection": "браслет",
        "season": "зима",
        "brand": "Chanel",
        "price": "30",
        "rarity": "10",
        "img": "https://diamant.uz/image/cache/catalog/products/251221.08/002/01-550x550-product_thumb.jpg",
    },
    {
        id: 3,
        "for": "партнеру",
        "developments": "день рождения",
        "collection": "цыпочка",
        "season": "весна",
        "brand": "Gucci",
        "price": "50",
        "rarity": "8",
        "img": "https://basket-02.wb.ru/vol173/part17366/17366823/images/big/2.jpg",
    },
    {
        id: 4,
        "for": "папе",
        "developments": "для себя",
        "collection": "браслет",
        "season": "осень",
        "brand": "Gucci",
        "price": "54",
        "rarity": "5",
        "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvTfeHEEWqNQ77ixGIEbaw8hq0xaCuUxkk6A&usqp=CAU",
    },
    {
        id: 5,
        "for": "маме",
        "developments": "день рождения",
        "collection": "серьги",
        "season": "лето",
        "brand": "Gucci",
        "price": "20",
        "rarity": "3",
        "img": "https://diamant.uz/image/cache/catalog/products/080421.03/008/01-550x550-product_thumb.jpg",
    },
    {
        id: 6,
        "for": "мужу",
        "developments": "свадьба",
        "collection": "коллекции",
        "season": "весна",
        "price": "54",
        "brand": "Zoodamall",
        "rarity": "7",
        "img": "https://diamant.ua/uploads/a0/37/a037cdec2d172730ce176586495a588f.jpg",
    },
    {
        id: 7,
        "for": "жене",
        "developments": "свадьба",
        "collection": "серьги",
        "season": "лето",
        "price": "62",
        "brand": "Chanel",
        "rarity": "7",
        "img": "https://mago.uz/upload/file/front/products/images/Fonon_ZIR0106QZ.jpg",
    },
    {
        id: 8,
        "for": "мужу",
        "developments": "день рождение",
        "collection": "браслет",
        "season": "осень",
        "price": "65",
        "brand": "Zoodamall", 
        "rarity": "8",
        "img": "https://engrave.uz/image/cache/catalog/other/32-350x350.png",
    },
    {
        id: 9,
        "for": "маме",
        "developments": "день рождение",
        "collection": "коллекции",
        "season": "весна",
        "brand": "Chanel",
        "price": "70",
        "rarity": "10",
        "img": "https://ae04.alicdn.com/kf/Hb0e9c9c09b76460480d8bdb2c8e4a599a/-.jpg_640x640.jpg",
    },
    {
        id: 10,
        "for": "мужу",
        "developments": "свадьба",
        "collection": "коллекции",
        "season": "весна",
        "price": "10",
        "brand": "Zoodamall", 
        "rarity": "7",
        "img": "https://bgs.kiev.ua/wp-content/uploads/Razmery-obruchalnykh-kolets-87-Bz.jpg",
    },

]

